### ISSUE TITLE
/model/predict endpoints fails on Red Hat OpenShift due to permission error

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Text-Summarizer#22]
```

INFO:tensorflow:Loading checkpoint /workspace/assets/model-238410
--
  | Traceback (most recent call last):
  | File "core/getpoint/run_summarization.py", line 334, in <module>
  | tf.app.run()
  | File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
  | _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  | File "core/getpoint/run_summarization.py", line 327, in main
  | decoder = BeamSearchDecoder(model, batcher, vocab)
  | File "/workspace/core/getpoint/decode.py", line 69, in __init__
  | if not os.path.exists(self._decode_dir): os.mkdir(self._decode_dir)
  | PermissionError: [Errno 13] Permission denied: '/workspace/assets/decode'


```

**Comment by xuhdev** [comment]
Fixed by #24
